### ISSUE TITLE
Add toast notifications to user actions

### ISSUE THREAD

**Issue by assumption** [cpe308-309/Group-name#108]

**Comment by BaconPartyWOOOO** [comment]
Completed in commits: 
57c683034bf164dfdfe642b7c6f00f6dc4ecb8fb
85e580a33dcb267d43ef2c20eb94b4bd74538671
333fe248e1def5e631016f97ee398c650106a407
57c683034bf164dfdfe642b7c6f00f6dc4ecb8fb
