### ISSUE TITLE
Implement the hamburger menu and drag and drop support for the flowchart

### ISSUE THREAD

**Issue by assumption** [cpe308-309/Group-name#23]
Create the hamburger menu and implement a demo of the drag and drop without API functionality

Advances vertical prototype in that the UI is pretty important

**Comment by assumption** [comment]
To appreciate the changes brought upon by this issue, please visit https://cp-groupname.herokuapp.com/

**Comment by gsocher** [comment]
awesome. Cool drag & drop!
